name:  Workflow for SAST Scan
on:  push
jobs:
  sonarcloud:
    runs-on:  ubuntu-latest
    steps:
    -  uses:  actions/checkout@v4
    -  name:  Set up JDK 17
       uses:  actions/setup-java@v4
       with:
         java-version:  '17'
         distribution:  'zulu'
         server-id:  github
         settings-path:  ${{  github.workspace  }}
         cache:  maven
    -  name:  Build with Maven
       run:  |
         mvn verify sonar:sonar \
         -Dsonar.projectKey=sonaranalysiseccounciltraining_codered  \
         -Dsonar.organization=sonaranalysiseccounciltraining  \
         -Dsonar.host.url=https://sonarcloud.io

       env:
         GITHUB_TOKEN:  ${{  secrets.GITHUB_TOKEN  }}
         SONAR_TOKEN:  ${{  secrets.SONAR_TOKEN  }}
         
